Author topic
MrLongbottom/P10-Code pull request #25
Opened 2021-04-08 09:13 UTC by slayeren

With a few changes to category

2021-04-09 08:11 UTC, Starrock45 requested changes

2021-04-09 08:11 UTC, Starrock45 commented on model/author_gibbs_lda.py
> +    :param cat_topic: a matrix describing the number of times each topic within each category
Gætter på at det skal ændres til 'aut_topic' eller noget lignende.

2021-04-09 08:11 UTC, Starrock45 commented on model/author_gibbs_lda.py
> +    model = Model(num_topics, alpha, beta, author_topic_dist, topic_word_dist, "category")
```suggestion
    model = Model(num_topics, alpha, beta, author_topic_dist, topic_word_dist, "author")
```

2021-04-12 09:38 UTC, MrLongbottom approved these changes
Vi skal lige omnavngive nogle ting fra category til author, men ellers ser det fint ud

2021-04-13 13:12 UTC, Starrock45 approved these changes

2021-04-14 07:08 UTC, merged