Generalized Pachinko
MrLongbottom/P10-Code pull request #27
Opened 2021-04-12 10:24 UTC by MrLongbottom

Pachinko med 3 lag.

2021-04-13 08:29 UTC, slayeren requested changes

2021-04-13 08:29 UTC, rasmus-e-christensen commented on model/pachinko_gibbs_lda.py
> +    topic_to_word_sums[topics[len(topics) - 1]] += 1
Move this to gibbs ultility and call it pachinko_increase_counts and pachinko_decrease_counts

2021-04-13 15:20 UTC, MrLongbottom commented on model/pachinko_gibbs_lda.py
> +    topic_to_word_sums[topics[len(topics) - 1]] += 1
hvis den er specifik kun til pachinko hvorfår så lægge den i en anden fil?

2021-04-14 07:47 UTC, slayeren commented on model/pachinko_gibbs_lda.py
> +    topic_to_word_sums[topics[len(topics) - 1]] += 1
true

2021-04-14 08:31 UTC, slayeren commented on model/pachinko_gibbs_lda.py
> +        # sims calculated to be used later
```suggestion
        # sums calculated to be used later
```

2021-04-14 08:34 UTC, slayeren approved these changes

2021-04-14 08:34 UTC, slayeren commented on model/pachinko_gibbs_lda.py
> +            # TODO make work for any number of dimensions (currently only working with 3 middle layers)
er dette gjort?

2021-04-14 12:13 UTC, MrLongbottom commented on model/pachinko_gibbs_lda.py
> +            # TODO make work for any number of dimensions (currently only working with 3 middle layers)
ja
```suggestion
```

2021-04-14 13:51 UTC, Starrock45 reviewed
Har et par kommentarer. Jeg har nok ikke forstået det hele fuldstændigt, men jeg har heller ikke læst pachinko artiklen endnu.

2021-04-14 13:51 UTC, Starrock45 commented on model/pachinko_gibbs_lda.py
> +                   wta,
Vil nok hellere have det skrevet ud, da det alligevel kun bruges 1 sted i koden

2021-04-14 13:51 UTC, Starrock45 commented on model/pachinko_gibbs_lda.py
> +    :param middle_layers:
Det ville være dejligt hvis `middle_layers` også blev beskrevet.

2021-04-14 13:51 UTC, Starrock45 commented on model/pachinko_gibbs_lda.py
> +            word_topic_assignment[d_index][w_index] = topic
Er nok mere passende at bruge `wta` fra parametrene, medmindre parameternavnet alligevel ændres.

2021-04-19 07:49 UTC, MrLongbottom commented on model/pachinko_gibbs_lda.py
> +                   wta,
altså i main? så bliver main nok meget lang, men det kan vi godt?

2021-04-19 07:49 UTC, MrLongbottom commented on model/pachinko_gibbs_lda.py
> +    :param middle_layers:
har opdateret til bare at bruge de variabler som er defineret i main, frem for at tage dem alle med som parametre

2021-04-19 08:51 UTC, Starrock45 commented on model/pachinko_gibbs_lda.py
> +                   wta,
```suggestion
                   word_topic_assignment,
```
Jeg tænkte sådan her, og så ændre den på linje 113. Linje 174 bruger nemlig også lige nu word_topic_assignment fra main.

2021-04-20 08:42 UTC, Starrock45 approved these changes

2021-04-20 13:54 UTC, MrLongbottom commented on model/pachinko_gibbs_lda.py
> +                   wta,
right forstår hvad du mener nu.

2021-04-20 14:02 UTC, merged