Category LDA with gibbs
MrLongbottom/P10-Code pull request #9
Opened 2021-03-04 14:46 UTC by slayeren

2021-03-05 09:38 UTC, MrLongbottom approved these changes

2021-03-10 10:43 UTC, Starrock45 requested changes

2021-03-10 10:43 UTC, Starrock45 commented on model/category_gibbs_lda.py
> +    :param cat_topic: a matrix describing the number of times each topic within each document
```suggestion
    :param cat_topic: a matrix describing the number of times each topic within each category
```

2021-03-10 10:43 UTC, Starrock45 commented on model/category_gibbs_lda.py
> +            c_index = doc2category[d_index]
```suggestion
        c_index = doc2category[d_index]
        for w_index, word in enumerate(doc):
            # Find the topic for the given word a decrease the topic count
            topic = word_topic_assignment[d_index][w_index]
```
Rykker `c_index` ud i doc løkken

2021-03-10 10:43 UTC, Starrock45 commented on model/category_gibbs_lda.py
> +            # Sample a new topic based on doc_topic and topic word
```suggestion
            # Sample a new topic based on cat_topic and topic word
```

2021-03-10 10:43 UTC, Starrock45 commented on model/category_gibbs_lda.py
> +    return coherence.coherence(topics=get_topics(), doc2bow=doc2bow, dictionary=dictionary, texts=texts)
De her funktioner kan muligvis rykkes over i en separat gibbs sampling utility fil, da de og funktionerne i model/gibbs_lda.py umiddelbart er ens.

2021-03-11 11:42 UTC, Starrock45 approved these changes

2021-03-11 13:44 UTC, merged